<?php

/**
 * @file
 * This file is used to write hooks that are used in the module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\simple_live_css\Utility\InjectCssFileUtility;

/**
 * Implements hook_page_attachments().
 */
function simple_live_css_page_attachments(array &$page) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute($route);
  if ($is_admin_route) {
    return;
  }

  $page['#attached']['library'][] = 'simple_live_css/simple_live_css';
  if (\Drupal::currentUser()->hasPermission('edit live css')) {
    $page['#attached']['library'][] = 'simple_live_css/simple_live_css_editor';
    $page['#attached']['drupalSettings']['simple_live_css']['css_file_path'] = InjectCssFileUtility::getRelativePath();
  }
}

/**
 * Implements hook_library_info_alter().
 */
function simple_live_css_library_info_alter(array &$libraries, $extension) {
  if ($extension === 'simple_live_css' && file_exists(InjectCssFileUtility::FILE_PATH)) {
    $relative_path = InjectCssFileUtility::getRelativePath();
    $libraries['simple_live_css']['css']['theme'][$relative_path] = [
      'preprocess' => FALSE,
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function simple_live_css_preprocess_html(array &$variables) {
  if (\Drupal::currentUser()->hasPermission('edit live css')) {
    $variables['attributes']['class'][] = 'js--live-css';
  }
}

/**
 * Implements hook_css_alter().
 *
 * Make sure the custom inject file is loaded last,
 * since we want to be able to override any (theme) css.
 *
 * @todo Refactor once conditional ordering is introduced in https://www.drupal.org/node/1945262.
 */
function simple_live_css_css_alter(&$css, AttachedAssetsInterface $assets) {
  $path = ltrim(InjectCssFileUtility::getRelativePath(), '/');
  if (isset($css[$path])) {
    $css[$path]['group'] = 300;
  }
}
