<?php
/**
 * Implementation of hook_theme().
 */

function amazing_forms_theme() {
	return [
    'fieldset_element' => [
    	'render element' => 'form', 
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK() for fieldset.
 */
// function template_preprocess_fieldset_element(&$variables) {
//   $form = $variables['form'];
//   $composite_types = ['checkboxes', 'radios'];

//   if (!empty($form['#type']) && in_array($form['#type'], $composite_types) && !empty($variables['form']['#children_errors'])) {
//     $variables['legend_span']['attributes']->addClass('has-error');
//   }

//   if (!empty($form['#disabled'])) {
//     $variables['legend_span']['attributes']->addClass('is-disabled');

//     if (!empty($variables['description']) && !empty($variables['description']['attributes'])) {
//       $variables['description']['attributes']->addClass('is-disabled');
//     }
//   }
//   // Remove 'container-inline' class from the main attributes and add a flag
//   // instead.
//   // @todo remove this after https://www.drupal.org/node/3059593 has been
//   //   resolved.
//   if (!empty($variables['attributes']['class'])) {
//     $container_inline_key = array_search('container-inline', $variables['attributes']['class']);

//     if ($container_inline_key !== FALSE) {
//       unset($variables['attributes']['class'][$container_inline_key]);
//       $variables['inline_items'] = TRUE;
//     }
//   }
// }

/**
 * Implementation of hook_form_alter().
 */
function amazing_forms_form_alter(&$form, $form_state, $form_id) {
	if($form_id == 'amazing_forms_contribute'){
		$form['my_captcha_element'] = array(
		        '#type' => 'captcha',
		        '#captcha_type' => 'recaptcha/reCAPTCHA',
		        '#weight' => 8,
		        );
		// $form['captcha']['#disabled'] = TRUE;
		}
		$form['fieldset']['#attached']['library'][] = 'amazing_forms/global-css';

} 

/**
 * Implementation of hook_captcha().
 */
function amazing_forms_captcha($captcha, $captcha_type='', $captcha_sid=NULL) {
	$result = image_captcha_captcha($captcha, $captcha_type='', $captcha_sid=NULL);
	
	// if($captcha == 'generate') {
	// 	$result['form']['captcha_response']['#title'] = t('Captcha Module');
	// }
	
	return $result;
}