name: Domain Configuration
description: 'Allows domain specific configuration.'
type: module
package: Domain
# version: VERSION
# core: 8.x
dependencies:
  - domain:domain

# Information added by Drupal.org packaging script on 2019-06-21
version: '8.x-1.0-alpha16'
core_version_requirement: ^8.9 || ^9
project: 'domain'
datestamp: 1561126090
